### ISSUE TITLE
Issues selecting items from drop down list

### ISSUE THREAD

**Issue by jthambly** [timklapdor/learning-materials#76]
While testing #74  I noticed that it can be sometimes difficult for the menu to stay open while trying to select an item from the drop-down list.

[2018-02-21_13-39-44.zip](https://github.com/timklapdor/learning-materials/files/1742690/2018-02-21_13-39-44.zip)

**Comment by jthambly** [comment]
Removed QA version, as it also exists in other areas:

Areas so far:

 - Grade Centre -> 'Sort Columns By'
 - Grade Centre -> 'Order'
 - Grade Centre -> Add Column -> Add Rubric (likley elsewhere too)

**Comment by jthambly** [comment]
yes, I can replicate (video provided in the zip file) - it will sometimes work, and sometimes not.
Some drop down menus (and it also may differ in theme versions) will have a larger gap between the input and the list. detecting the larger gap, it is possible that js thinks it is ok to close.

**Comment by jthambly** [comment]
Re-tested in QA (assume an update has been recently made) - the following has been fixed (likely due to less gap)

Grade Centre -> 'Sort Columns By'
Grade Centre -> 'Order'

Still an issue with Rubrics (another vid. attached).

Rubric1 taken from Grade Centre
Rubric2 taken from Discussion Board

[Rubrics.zip](https://github.com/timklapdor/learning-materials/files/1747202/Rubrics.zip)

**Comment by jthambly** [comment]
Another common area is under Grade Centre -> Manage -> Column Organisation - drop-down lists may, or may not work under here - when the issue occurs, it can sometimes be difficult to workaround this issue.

**Comment by Emrys78** [comment]
This *should* be fixed in dev now please check and we can upl;oad to QA:

https://interact2devel.csu.edu.au/

**Comment by jthambly** [comment]
Sure, I will need to wait until I have access to devel again before I can check.

**Comment by jthambly** [comment]
It will be unlikely that I would have access to devel for a little while, it may be best to have this put onto QA anyway as this is where most SaaS UAT is occurring. More chance of this issue in other areas being picked up.

**Comment by jthambly** [comment]
Checking under devel (theme test account) in Win10/Chrome - this is occurring in some areas, for example:

- Adding a rubric under the discussion board settings "Grade Discussion Form" -> "Add Rubric"
- Adding a rubric under a grade centre column (either when creating, or editing)
- Grade Centre: Manage -> Column Organisation -> Bottom: 'Show/Hide", "Change Category To...", "Grading Period To...",

**Comment by kxh210** [comment]
This is still an issue in adding rubrics to the Blackboard tools such as the Journal or Blog. Is there a fix coming?
